<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS8trgmC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS8trgmC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS8trgmC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS8trgmC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS8trgmC\App_KernelDevDebugContainer([
    'container.build_hash' => 'S8trgmC',
    'container.build_id' => '3964fdb0',
    'container.build_time' => 1771684060,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS8trgmC');
