<?php

namespace ContainerCG7zhxb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportDepartementCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ImportDepartementCommand' shared autowired service.
     *
     * @return \App\Command\ImportDepartementCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'ImportDepartementCommand.php';

        $container->privates['App\\Command\\ImportDepartementCommand'] = $instance = new \App\Command\ImportDepartementCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:import:departement');
        $instance->setDescription('Import des départements depuis un CSV');

        return $instance;
    }
}
